### ISSUE TITLE
invest_json() changes

### ISSUE THREAD

**Issue by ghost** [mintapi/mintapi#227]
looks like mint has deprecated the old https://mint.intuit.com/investment.event api and moved to 
https://mint.intuit.com/investment-new.event. Is this repo still active? Lots of cool new things here. I'm considering becoming a contributor.

**Comment by mrooney** [comment]
Yes, it is quite active! We always welcome contributions and PRs are
regularly merged :) Are you comfortable submitting a PR using the new API?

**Comment by ljc-codes** [comment]
That sounds awesome! Yeah, little busy with life stuff right now but I'll give it a shot in the coming weeks and shoot you guys a pull request! 

Best
Tiger Shark

**Comment by burkematthew** [comment]
It looks like we do not currently support `get_invests_json` from the command-line, which is the method that actually makes this request.  @mrooney are you good with this change including adding support for `get_invests_json` from the command-line, while also switching over to the new endpoint?

**Comment by mrooney** [comment]
> It looks like we do not currently support `get_invests_json` from the command-line, which is the method that actually makes this request. @mrooney are you good with this change including adding support for `get_invests_json` from the command-line, while also switching over to the new endpoint?

Sounds like a great approach all around, thanks!

**Comment by burkematthew** [comment]
@jaron-l @mrooney I've got this working well on the draft PR submitted.  However, I do want to point out that the data structure does change, which could be a breaking change for some users.  How do we want to approach this?  I could simply add a new method that handles the new endpoint, while preserving the old method for those that use it.  In addition, since command-line doesn't exist at the moment at all for investment data, I could point the command-line option to the new endpoint.

Thoughts?

**Comment by jaron-l** [comment]
> @jaron-l @mrooney I've got this working well on the draft PR submitted. However, I do want to point out that the data structure does change, which could be a breaking change for some users. How do we want to approach this? I could simply add a new method that handles the new endpoint, while preserving the old method for those that use it. In addition, since command-line doesn't exist at the moment at all for investment data, I could point the command-line option to the new endpoint.
> 
> Thoughts?

Does the old method work? I thought the point was that the old endpoint fails. If the old method *does* work, then I would create a new public method and mark the old one for deprecation if you feel it should no longer be supported. You can see how I did that [here](https://github.com/mintapi/mintapi/pull/336/files#diff-420df6d2848df13c8b3e980ecabc8b151c54ed9cb66e44fb44ae42af2e5cec8dR461). If the old method *doesn't* work, I would recommend we start a `v2` branch and start working on our next major release and form the PR against that. There we could throw several breaking changes at it before we release (I have a couple in mind). We should indicate that there has been a breaking change in the API and follow [semantic versioning](https://semver.org).

In either case, the command line can be added to support the "better" method since it wasn't supported before. I don't know if I understand what the difference between the two methods is if they both work.

**Comment by burkematthew** [comment]
@jaron-l yes, the old method works.  I was under that impression as well.  

And I agree on that approach.  I'll go ahead and do that.  Thanks!

**Comment by jaron-l** [comment]
What's the difference between the old and the new? Like what information is returned? What does the original author mean when they say it's deprecated?

**Comment by burkematthew** [comment]
@jaron-l from what I can tell, the old endpoint was just returning an HTML page to render.  The old routine would then strip out the data from that HTML page to return as the data.  In some ways, it does have more data, such as if an account is a retirement or brokerage account.  However, I would imagine that if Mint moved to the new endpoint, then there is a plan for them to actually deprecate it.  Because of that, I think this is the right approach for us to take.
