### ISSUE TITLE
Downloading non-stable Chrome driver causing errors

### ISSUE THREAD

**Issue by pazwicker** [mintapi/mintapi#271]
Starting today, my mint-api runs have downloaded chrome driver version 93 when the current, stable version is 92. This causes the scripts to fail because of a version mismatch. 

I've tried 
- manually downloading 92 driver but mint-api just overwrites it with 93 again
- installing the chrome beta (v93) but I hit the same issue because chrome stable is still installed

Anyone else experiencing this? I'm running Ubuntu 20.04 and I have a cron job running the mint scripts hourly. I've had hourly runs going to about 6 months without many hiccups. Just today this issue started appearing. Just updated to the newest mint-api via pip today while troubleshooting.

**Comment by pisakhov** [comment]
I use Amazon Lightsail, ubuntu 20 as well.

I used this tutorial https://tecadmin.net/install-google-chrome-on-ubuntu-20-04/

For some reason, it works only when I disable the two-step-verification

**Comment by jaron-l** [comment]
This is a bug with the logic to get the chromedriver downloaded. As a workaround, download the correct one and set `use_chromedriver_on_path=True` (and then make sure it is in the path somehow).

**Comment by jaron-l** [comment]
Hmm... I take it back. I don't think it's that it's downloading an unstable chromedriver, it's just that your machine hasn't updated to the most recent chrome version yet. Does this problem persist? It might be better to detect the chrome version of what is in your path and then download that version rather than just get the latest. Let me know if you continue to see this issue and perhaps we can investigate this solution.

**Comment by pazwicker** [comment]
@jaron-l this is no longer an issue, at least for me.
