### ISSUE TITLE
add intuit_account support to command-line options

### ISSUE THREAD

**Issue by mrooney** [mintapi/mintapi#314]
#252 added support for this in the code via Python, but we should have a command-line option and updated README :)

**Comment by burkematthew** [comment]
@jasonkissinger Is the `intuit_account` functionality that this issue relates to actually working?  I started working on implementing the command-line option and it appears that we hang in a try\except loop.  If you are able to successfully use this functionality, I'll keep pushing through to see what I'm doing wrong.  Otherwise, I'll explore a bug fix in conjunction.

**Comment by jasonkissinger** [comment]
It worked a few months ago but I've abandoned the project which uses it so
haven't tried in awhile.  I've noticed that the login UI has changed
recently so I wouldn't doubt it no longer works.

**Comment by burkematthew** [comment]
@jasonkissinger got it, thanks for the update!
