### ISSUE TITLE
Pending transactions are shown -- "show_pending" attribute is causing error

### ISSUE THREAD

**Issue by cobbmic** [mintapi/mintapi#437]
This is probably just a mistake on my end. But I use mintapi to pull transactions and format them for my ledger-cli files. However, it is pulling in pending transactions. 95% of the time, that's not a problem. But with transactions at restaurants or coffeeshops where I leave a tip, the tip is often not included in the amount when it is pending. It is corrected when the transaction clears.

So I don't want to get pending transactions.

I currently pull my data within a custom python script. The relevant section is:
`csvData = mint.get_transactions_csv(include_investment=False, start_date=day_start, end_date=day_end)`

I tried changing it to:

`csvData = mint.get_transactions_csv(include_investment=False, start_date=day_start, end_date=day_end, show_pending=False)`

to see how toggling the "show_pending" attribute affects the problem.  I got the following error:

>TypeError: Mint.get_transactions_csv() got an unexpected keyword argument 'show_pending'

Looking through the source code, it appears that the "show_pending" attribute is only for the command line usage of MintAPI? Is there a way to access it through the get_transactions_csv method? If not, it'd be nice if that attribute was added.

**Comment by burkematthew** [comment]
@cobbmic thanks for the report! That method is actually about to be removed with the new major version of 2.0. That being said, the new `get_transaction_data` method that handles all transaction related requests does expose that option regardless of CLI or your own script. If you have the new UI from Mint, you can work off of the main branch of the repo instead of the installed version of PyPi to get this. If you'd prefer to wait, though, we should have the next release completed in the next week or two.

**Comment by cobbmic** [comment]
Awesome!
