### ISSUE TITLE
Unable to find corresponding information to merchantId returned in get_transaction_data call

### ISSUE THREAD

**Issue by KOEPKEJR** [mintapi/mintapi#481]
Version 1.x returned a 'merchant' column which could be filtered.  The column was human readable and had values such as 'Target'.  The 2.x dataset no longer has the 'merchant' column but does have a potentially useful 'merchantId' column.  There is a 'description' field that has similar data but doesn't appear to be as static as the previous 'merchant' field.  

Is it possible that a merchant end-point exists?  Of note is that some transactions have a NaN merchantId.

**Comment by burkematthew** [comment]
This is very do-able. Barring any restrictions from Mint, we'll add support for merchants data like we did with categories.

**Comment by burkematthew** [comment]
So far, the following endpoints do not exist for Mint:

* pfm/v1/merchant
* pfm/v1/merchants
* pfm/v1/vendor
* pfm/v1/vendors

If you go to manually add a transaction in Mint, here is the screen:

<img width="727" alt="Screen Shot 2022-06-18 at 10 24 02 AM" src="https://user-images.githubusercontent.com/22505475/174445453-14bf99fa-7ec4-446c-beac-d37bd4aa985b.png">

If you notice, the description has the prompt of "add merchant name".  In fact, when looking in the app where it asks to "choose a merchant", it's really just a distinct list of values for my description field.  I get the impression that Mint is moving away from maintaining a list of merchants.  It may just be exposed for current backwards compatibility.

All this being said, this is not something that we can do.  If evaluating the description for the merchant isn't sufficient, I'd recommend taking the distinct merchant IDs, cross-referencing it to the associated description, and building your own table.  That or ignore the value of the merchant ID and just use character matching to figure out what the merchant is since depending on the store, location, etc., the description may be slightly different.

I know this isn't the answer any of us were hoping for, but appears the reality of what is in Mint.

**Comment by burkematthew** [comment]
@KOEPKEJR @andrewjlaird unfortunately, no good news on this front.

**Comment by KOEPKEJR** [comment]
@burkematthew I appreciate the investigation.  Thanks for all you do on the project.
